package main

import "fmt"
import ".."

func main() {
	fmt.Printf("\n")
	fmt.Printf("  Styles: ")
	fmt.Printf("\n")
	fmt.Printf("\n")
	fmt.Printf("    bold: %s \n", colors.Print("bold", "bold"))
	fmt.Printf("    italic: %s \n", colors.Print("italic", "italic"))
	fmt.Printf("    underline: %s \n", colors.Print("underline", "underline"))
	fmt.Printf("    inverse: %s \n", colors.Print("inverse", "inverse"))
	fmt.Printf("    strikethrough: %s \n", colors.Print("strikethrough", "strikethrough"))
	fmt.Printf("\n")
	fmt.Printf("  Grayscale: \n")
	fmt.Printf("\n")
	fmt.Printf("    white: %s \n", colors.Print("white", "white"))
	fmt.Printf("    grey: %s \n", colors.Print("grey", "grey"))
	fmt.Printf("    black: %s \n", colors.Print("black", "black"))
	fmt.Printf("\n")
	fmt.Printf("  Colors list: \n")
	fmt.Printf("\n")
	fmt.Printf("    %s \n", colors.Print("blue", "blue"))
	fmt.Printf("    %s \n", colors.Print("cyan", "cyan"))
	fmt.Printf("    %s \n", colors.Print("green", "green"))
	fmt.Printf("    %s \n", colors.Print("magenta", "magenta"))
	fmt.Printf("    %s \n", colors.Print("red", "red"))
	fmt.Printf("    %s \n", colors.Print("yellow", "yellow"))
	fmt.Printf("\n")
	fmt.Printf("  Background colors: \n")
	fmt.Printf("\n")
	fmt.Printf("    %s \n", colors.Print("whiteBG", "whiteBG"))
	fmt.Printf("    %s \n", colors.Print("greyBG", "greyBG"))
	fmt.Printf("    %s \n", colors.Print("blackBG", "blackBG"))
	fmt.Printf("    %s \n", colors.Print("blueBG", "blueBG"))
	fmt.Printf("    %s \n", colors.Print("cyanBG", "cyanBG"))
	fmt.Printf("    %s \n", colors.Print("greenBG", "greenBG"))
	fmt.Printf("    %s \n", colors.Print("magentaBG", "magentaBG"))
	fmt.Printf("    %s \n", colors.Print("redBG", "redBG"))
	fmt.Printf("    %s \n", colors.Print("yellowBG", "yellowBG"))
	fmt.Printf("\n")
}
