package main

import "fmt"
import . ".."

func main() {
	fmt.Printf("\n")
	fmt.Printf("  Styles: ")
	fmt.Printf("\n")
	fmt.Printf("\n")
	fmt.Printf("    bold: %s \n", Color("bold", "bold"))
	fmt.Printf("    italic: %s \n", Color("italic", "italic"))
	fmt.Printf("    underline: %s \n", Color("underline", "underline"))
	fmt.Printf("    inverse: %s \n", Color("inverse", "inverse"))
	fmt.Printf("    strikethrough: %s \n", Color("strikethrough", "strikethrough"))
	fmt.Printf("\n")
	fmt.Printf("  Grayscale: \n")
	fmt.Printf("\n")
	fmt.Printf("    white: %s \n", Color("white", "white"))
	fmt.Printf("    grey: %s \n", Color("grey", "grey"))
	fmt.Printf("    black: %s \n", Color("black", "black"))
	fmt.Printf("\n")
	fmt.Printf("  Colors list: \n")
	fmt.Printf("\n")
	fmt.Printf("    %s \n", Color("blue", "blue"))
	fmt.Printf("    %s \n", Color("cyan", "cyan"))
	fmt.Printf("    %s \n", Color("green", "green"))
	fmt.Printf("    %s \n", Color("magenta", "magenta"))
	fmt.Printf("    %s \n", Color("red", "red"))
	fmt.Printf("    %s \n", Color("yellow", "yellow"))
	fmt.Printf("\n")
	fmt.Printf("  Background colors: \n")
	fmt.Printf("\n")
	fmt.Printf("    %s \n", Color("whiteBG", "whiteBG"))
	fmt.Printf("    %s \n", Color("greyBG", "greyBG"))
	fmt.Printf("    %s \n", Color("blackBG", "blackBG"))
	fmt.Printf("    %s \n", Color("blueBG", "blueBG"))
	fmt.Printf("    %s \n", Color("cyanBG", "cyanBG"))
	fmt.Printf("    %s \n", Color("greenBG", "greenBG"))
	fmt.Printf("    %s \n", Color("magentaBG", "magentaBG"))
	fmt.Printf("    %s \n", Color("redBG", "redBG"))
	fmt.Printf("    %s \n", Color("yellowBG", "yellowBG"))
	fmt.Printf("\n")
}
